/**
 * Job Notification Tracker
 * Dataset: 60 realistic Indian tech jobs
 */

const JOBS_DATA = [
  {
    id: 1,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.amazon.jobs/",
    description: "Join Amazon's internship program to work on cutting-edge projects. You'll collaborate with experienced engineers, learn best practices, and contribute to real-world solutions. Ideal for students passionate about software development and eager to grow."
  },
  {
    id: 2,
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Spring Boot", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.tcs.com/careers",
    description: "TCS Graduate Engineer Trainee program offers comprehensive training in enterprise software development. You'll work on client projects, learn industry-standard tools, and build a strong foundation for your career in IT services."
  },
  {
    id: 3,
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://careers.razorpay.com/",
    description: "Build scalable payment infrastructure at Razorpay. Work on microservices architecture, handle high-volume transactions, and solve complex technical challenges. Great learning opportunity in fintech."
  },
  {
    id: 4,
    title: "Frontend Intern",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "HTML"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.zoho.com/careers/internship",
    description: "Create beautiful user interfaces for Zoho's suite of products. Learn React best practices, work with design systems, and contribute to products used by millions. Perfect for frontend enthusiasts."
  },
  {
    id: 5,
    title: "QA Intern",
    company: "Wipro",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "TestNG", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.wipro.com/internship",
    description: "Learn quality assurance practices at Wipro. You'll test enterprise applications, write test cases, automate testing workflows, and ensure software quality. Great entry point into QA career."
  },
  {
    id: 6,
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "SQL", "Pandas", "Data Visualization"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Analyze e-commerce data to drive business decisions at Flipkart. Work with large datasets, create dashboards, and provide insights to product teams. Ideal for data science enthusiasts."
  },
  {
    id: 7,
    title: "Java Developer (0-1)",
    company: "Infosys",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.infosys.com/careers",
    description: "Develop enterprise Java applications at Infosys. Work on client projects, learn Spring framework, and build robust backend systems. Comprehensive training and mentorship provided."
  },
  {
    id: 8,
    title: "Python Developer (Fresher)",
    company: "Accenture",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Git"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.accenture.com/in-en/careers",
    description: "Build web applications using Python and Django at Accenture. Work on diverse projects, learn agile methodologies, and grow your skills in a supportive environment."
  },
  {
    id: 9,
    title: "React Developer (1-3)",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.freshworks.com/company/careers/",
    description: "Build modern SaaS products at Freshworks using React and TypeScript. Work on complex UIs, optimize performance, and contribute to products loved by customers worldwide."
  },
  {
    id: 10,
    title: "SDE Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "React", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Work on Swiggy's food delivery platform. Build features that impact millions of users, learn scalable architecture, and solve real-world problems in a fast-paced startup environment."
  },
  {
    id: 11,
    title: "Backend Developer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Kafka", "Cassandra"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.phonepe.com/careers",
    description: "Build payment infrastructure at PhonePe. Work on high-throughput systems, handle millions of transactions, and ensure reliability. Great opportunity to work on fintech at scale."
  },
  {
    id: 12,
    title: "Frontend Developer",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "CSS", "Webpack"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://paytm.com/careers",
    description: "Create user interfaces for Paytm's financial products. Work on responsive designs, optimize performance, and build features used by millions of Indians daily."
  },
  {
    id: 13,
    title: "Full Stack Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "Node.js", "MongoDB", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Build features for CRED's credit card rewards platform. Work on both frontend and backend, learn modern tech stack, and contribute to a product with premium user experience."
  },
  {
    id: 14,
    title: "DevOps Intern",
    company: "Capgemini",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Docker", "Kubernetes", "AWS", "Jenkins"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.capgemini.com/careers",
    description: "Learn DevOps practices at Capgemini. Work on CI/CD pipelines, containerization, cloud infrastructure, and automation. Great foundation for infrastructure engineering career."
  },
  {
    id: 15,
    title: "Mobile Developer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React Native", "JavaScript", "Redux", "Android"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.juspay.in/careers",
    description: "Build mobile payment SDKs at Juspay. Work on React Native apps, optimize performance, and ensure seamless payment experiences across Android and iOS platforms."
  },
  {
    id: 16,
    title: "Data Engineer",
    company: "Cognizant",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Spark", "Hadoop", "SQL"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.cognizant.com/in/en/careers",
    description: "Build data pipelines and analytics solutions at Cognizant. Work with big data technologies, process large datasets, and enable data-driven decision making for clients."
  },
  {
    id: 17,
    title: "UI/UX Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Figma", "Adobe XD", "Prototyping", "User Research"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.ibm.com/careers",
    description: "Design user experiences for IBM's enterprise software. Learn design thinking, create prototypes, conduct user research, and work with cross-functional teams to build great products."
  },
  {
    id: 18,
    title: "Backend Intern",
    company: "Oracle",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Oracle DB", "REST APIs", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.oracle.com/careers",
    description: "Work on Oracle's cloud services backend. Learn enterprise architecture, work with databases, and build scalable APIs. Great opportunity to learn from industry leaders."
  },
  {
    id: 19,
    title: "Full Stack Developer",
    company: "SAP",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["JavaScript", "Node.js", "React", "SAP HANA"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.sap.com/company/careers",
    description: "Build enterprise applications on SAP platform. Work with SAP technologies, modern web frameworks, and create solutions for global clients. Comprehensive training provided."
  },
  {
    id: 20,
    title: "Cloud Engineer",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["AWS", "Terraform", "Python", "Linux"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.dell.com/en-in/careers",
    description: "Design and manage cloud infrastructure at Dell. Work with AWS services, automate deployments, ensure security, and optimize costs. Great for cloud career growth."
  },
  {
    id: 21,
    title: "SDE Intern",
    company: "TechVista Solutions",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Django", "React", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Join a fast-growing startup building SaaS products. Work on full-stack features, learn startup culture, and make direct impact. Great learning environment with mentorship."
  },
  {
    id: 22,
    title: "Junior Developer",
    company: "DataSync Technologies",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "Flask", "SQL", "Git"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/",
    description: "Build data processing applications at DataSync. Work on ETL pipelines, APIs, and data visualization. Learn from experienced developers in a collaborative environment."
  },
  {
    id: 23,
    title: "Frontend Intern",
    company: "CloudNine Solutions",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Vue.js", "JavaScript", "CSS", "Tailwind"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.co.in/",
    description: "Create modern web interfaces using Vue.js. Work on responsive designs, component libraries, and user experience. Perfect for frontend development enthusiasts."
  },
  {
    id: 24,
    title: "Backend Developer",
    company: "SecureNet Systems",
    location: "Hyderabad",
    mode: "Remote",
    experience: "1-3",
    skills: ["Node.js", "Express", "MongoDB", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Build secure backend systems for cybersecurity products. Work on authentication, APIs, and data processing. Learn security best practices and scalable architecture."
  },
  {
    id: 25,
    title: "QA Engineer",
    company: "AppFlow Dynamics",
    location: "Chennai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Selenium", "Java", "TestNG", "API Testing"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/",
    description: "Ensure quality of mobile and web applications. Write test cases, automate testing, and work with development teams. Great entry point into QA engineering."
  },
  {
    id: 26,
    title: "Data Science Intern",
    company: "AnalyticsPro",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Machine Learning", "Pandas", "Scikit-learn"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.co.in/",
    description: "Build ML models and analyze data at AnalyticsPro. Work on real-world datasets, learn data science workflows, and contribute to client projects. Ideal for ML enthusiasts."
  },
  {
    id: 27,
    title: "Full Stack Developer",
    company: "WebCraft Studios",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["MERN Stack", "TypeScript", "Docker", "AWS"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Build end-to-end web applications at WebCraft. Work on modern tech stack, deploy to cloud, and create products from scratch. Great for full-stack skill development."
  },
  {
    id: 28,
    title: "DevOps Engineer",
    company: "InfraCloud Systems",
    location: "Pune",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Kubernetes", "Docker", "CI/CD", "Monitoring"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.naukri.com/",
    description: "Manage cloud infrastructure and CI/CD pipelines. Work with Kubernetes, automate deployments, monitor systems, and ensure high availability. Great DevOps learning opportunity."
  },
  {
    id: 29,
    title: "Mobile App Developer",
    company: "AppGenius Labs",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Flutter", "Dart", "Firebase", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.indeed.co.in/",
    description: "Build cross-platform mobile apps using Flutter. Work on UI/UX, integrate APIs, and publish apps to stores. Great for mobile development career start."
  },
  {
    id: 30,
    title: "Backend Intern",
    company: "APIForge",
    location: "Hyderabad",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Build RESTful APIs and microservices at APIForge. Learn modern Python frameworks, database design, and API best practices. Perfect for backend learning."
  },
  {
    id: 31,
    title: "Frontend Developer",
    company: "UI Innovations",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.naukri.com/",
    description: "Create modern web experiences using React and Next.js. Work on performance optimization, SEO, and build scalable frontend architecture. Great React learning opportunity."
  },
  {
    id: 32,
    title: "SDE Intern",
    company: "CodeCraft Solutions",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Spring Boot", "React", "MySQL"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.co.in/",
    description: "Work on enterprise software development at CodeCraft. Learn Java ecosystem, build full-stack features, and gain industry experience. Comprehensive mentorship provided."
  },
  {
    id: 33,
    title: "Data Engineer",
    company: "BigData Labs",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Spark", "Airflow", "BigQuery"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Build data pipelines and analytics infrastructure. Work with big data tools, schedule workflows, and enable data-driven insights. Great for data engineering career."
  },
  {
    id: 34,
    title: "Full Stack Intern",
    company: "StartupHub",
    location: "Pune",
    mode: "Remote",
    experience: "Fresher",
    skills: ["MERN Stack", "Git", "Deployment", "Agile"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.naukri.com/",
    description: "Join a vibrant startup building innovative products. Work on full-stack features, learn startup culture, and make direct impact. Fast-paced learning environment."
  },
  {
    id: 35,
    title: "Backend Developer",
    company: "MicroServices Inc",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Go", "Microservices", "Docker", "Kubernetes"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.indeed.co.in/",
    description: "Build microservices architecture using Go. Work on distributed systems, learn containerization, and build scalable backend services. Great for modern backend skills."
  },
  {
    id: 36,
    title: "QA Automation Engineer",
    company: "TestPro Solutions",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Cypress", "JavaScript", "API Testing", "CI/CD"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Automate testing for web and mobile applications. Write test scripts, integrate with CI/CD, and ensure quality. Great for QA automation career growth."
  },
  {
    id: 37,
    title: "Frontend Intern",
    company: "DesignTech",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "CSS", "JavaScript", "Figma"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.naukri.com/",
    description: "Build beautiful user interfaces at DesignTech. Work closely with designers, implement designs, and create engaging user experiences. Perfect for frontend enthusiasts."
  },
  {
    id: 38,
    title: "DevOps Intern",
    company: "CloudOps India",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["AWS", "Docker", "Git", "Linux"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.co.in/",
    description: "Learn cloud infrastructure and DevOps practices. Work on AWS services, containerization, and automation. Great foundation for infrastructure engineering career."
  },
  {
    id: 39,
    title: "Backend Developer",
    company: "ServerStack",
    location: "Pune",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Python", "Django", "PostgreSQL", "Celery"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Build scalable backend systems using Python and Django. Work on APIs, background jobs, and database optimization. Great Python backend learning opportunity."
  },
  {
    id: 40,
    title: "Full Stack Developer",
    company: "TechFlow",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["JavaScript", "Node.js", "React", "MongoDB"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/",
    description: "Build end-to-end web applications at TechFlow. Work on modern JavaScript stack, learn full-stack development, and contribute to product features."
  },
  {
    id: 41,
    title: "SDE Intern",
    company: "InnovateLab",
    location: "Chennai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Flask", "React", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.co.in/",
    description: "Work on innovative projects at InnovateLab. Build web applications, learn modern frameworks, and solve interesting problems. Great learning environment."
  },
  {
    id: 42,
    title: "Data Analyst",
    company: "InsightAnalytics",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["SQL", "Python", "Tableau", "Excel"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Analyze business data and create insights at InsightAnalytics. Work with SQL, build dashboards, and help teams make data-driven decisions. Great analytics career start."
  },
  {
    id: 43,
    title: "Mobile Developer",
    company: "AppVenture",
    location: "Mumbai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React Native", "TypeScript", "Firebase", "Redux"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.naukri.com/",
    description: "Build cross-platform mobile apps at AppVenture. Work on React Native, integrate backend services, and create smooth user experiences. Great mobile dev opportunity."
  },
  {
    id: 44,
    title: "Backend Intern",
    company: "ServerCraft",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Node.js", "Express", "MongoDB", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.co.in/",
    description: "Learn backend development with Node.js at ServerCraft. Build REST APIs, work with databases, and understand server architecture. Perfect backend learning opportunity."
  },
  {
    id: 45,
    title: "Frontend Developer",
    company: "WebFlow",
    location: "Hyderabad",
    mode: "Remote",
    experience: "0-1",
    skills: ["Vue.js", "JavaScript", "CSS", "Webpack"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Create modern web interfaces using Vue.js. Work on component architecture, optimize performance, and build responsive designs. Great Vue.js learning opportunity."
  },
  {
    id: 46,
    title: "QA Engineer",
    company: "QualityAssure",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Selenium", "Python", "Pytest", "Jenkins"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.naukri.com/",
    description: "Ensure software quality at QualityAssure. Write automated tests, work with CI/CD, and collaborate with development teams. Great QA engineering opportunity."
  },
  {
    id: 47,
    title: "Full Stack Intern",
    company: "DevStudio",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["MERN Stack", "Git", "Deployment", "Agile"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.co.in/",
    description: "Build full-stack applications at DevStudio. Learn MERN stack, work on real projects, and gain industry experience. Comprehensive mentorship provided."
  },
  {
    id: 48,
    title: "DevOps Engineer",
    company: "InfraScale",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Kubernetes", "AWS", "Terraform", "GitLab CI"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Manage cloud infrastructure and automation at InfraScale. Work with Kubernetes, infrastructure as code, and CI/CD pipelines. Great DevOps career opportunity."
  },
  {
    id: 49,
    title: "Backend Developer",
    company: "APIGateway",
    location: "Pune",
    mode: "Remote",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL", "Redis"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/",
    description: "Build RESTful APIs and microservices using Java Spring Boot. Work on backend architecture, database design, and API development. Great Java backend learning."
  },
  {
    id: 50,
    title: "Data Science Intern",
    company: "MLForge",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "ML", "Pandas", "Scikit-learn"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.co.in/",
    description: "Build machine learning models at MLForge. Work on real datasets, learn ML workflows, and contribute to AI projects. Perfect for data science enthusiasts."
  },
  {
    id: 51,
    title: "Frontend Developer",
    company: "UIStudio",
    location: "Chennai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "TypeScript", "Next.js", "Tailwind"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Create modern web experiences using React and Next.js at UIStudio. Work on performance, SEO, and build scalable frontend. Great React development opportunity."
  },
  {
    id: 52,
    title: "SDE Intern",
    company: "CodeBase",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "React", "PostgreSQL"],
    source: "Naukri",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.naukri.com/",
    description: "Work on full-stack development at CodeBase. Learn Django and React, build features, and gain real-world experience. Great learning environment with mentorship."
  },
  {
    id: 53,
    title: "Backend Developer",
    company: "MicroAPI",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["Node.js", "Express", "MongoDB", "GraphQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.indeed.co.in/",
    description: "Build GraphQL APIs and microservices at MicroAPI. Work on modern backend architecture, learn GraphQL, and build scalable systems. Great backend opportunity."
  },
  {
    id: 54,
    title: "QA Automation",
    company: "TestAutomation Pro",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Playwright", "TypeScript", "API Testing", "CI/CD"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Automate testing workflows at TestAutomation Pro. Learn Playwright, write test scripts, and integrate with CI/CD. Great QA automation learning opportunity."
  },
  {
    id: 55,
    title: "Full Stack Developer",
    company: "StackBuild",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "1-3",
    skills: ["MERN Stack", "TypeScript", "Docker", "AWS"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.naukri.com/",
    description: "Build end-to-end applications at StackBuild. Work on MERN stack, deploy to cloud, and create products from scratch. Great full-stack development opportunity."
  },
  {
    id: 56,
    title: "DevOps Intern",
    company: "CloudNative",
    location: "Chennai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Kubernetes", "Docker", "AWS", "Git"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.indeed.co.in/",
    description: "Learn cloud-native technologies at CloudNative. Work with Kubernetes, containers, and cloud services. Great foundation for DevOps and infrastructure career."
  },
  {
    id: 57,
    title: "Mobile Developer",
    company: "AppMakers",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Flutter", "Dart", "Firebase", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Build cross-platform mobile apps using Flutter at AppMakers. Work on UI/UX, integrate APIs, and publish apps. Great mobile development opportunity."
  },
  {
    id: 58,
    title: "Backend Intern",
    company: "ServerSide",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.naukri.com/",
    description: "Learn backend development with Python FastAPI at ServerSide. Build APIs, work with databases, and understand microservices. Perfect backend learning."
  },
  {
    id: 59,
    title: "Frontend Developer",
    company: "WebDesign Pro",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "CSS", "Webpack"],
    source: "LinkedIn",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.indeed.co.in/",
    description: "Create modern web interfaces at WebDesign Pro. Work on React components, optimize performance, and build responsive designs. Great frontend learning opportunity."
  },
  {
    id: 60,
    title: "Data Engineer",
    company: "DataPipeline",
    location: "Hyderabad",
    mode: "Remote",
    experience: "1-3",
    skills: ["Python", "Spark", "Airflow", "PostgreSQL"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/",
    description: "Build data pipelines and ETL workflows at DataPipeline. Work with big data tools, schedule jobs, and enable analytics. Great data engineering opportunity."
  }
];
